//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarethMod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GarethmodResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GarethmodResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarethMod.GarethmodResources", typeof(GarethmodResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_archerfish {
            get {
                object obj = ResourceManager.GetObject("garethmod_archerfish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_archerfish_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_archerfish_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_drawally {
            get {
                object obj = ResourceManager.GetObject("garethmod_drawally", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_elephant {
            get {
                object obj = ResourceManager.GetObject("garethmod_elephant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_elephant_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_elephant_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_gambler {
            get {
                object obj = ResourceManager.GetObject("garethmod_gambler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_gareth48 {
            get {
                object obj = ResourceManager.GetObject("garethmod_gareth48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_gareth48_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_gareth48_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_golem {
            get {
                object obj = ResourceManager.GetObject("garethmod_golem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_golem_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_golem_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_herculesbeetle {
            get {
                object obj = ResourceManager.GetObject("garethmod_herculesbeetle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_herculesbeetle_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_herculesbeetle_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_hungry {
            get {
                object obj = ResourceManager.GetObject("garethmod_hungry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_hyena {
            get {
                object obj = ResourceManager.GetObject("garethmod_hyena", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_hyena_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_hyena_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_identitytheft {
            get {
                object obj = ResourceManager.GetObject("garethmod_identitytheft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_killerbees {
            get {
                object obj = ResourceManager.GetObject("garethmod_killerbees", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_killerbees_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_killerbees_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lemming {
            get {
                object obj = ResourceManager.GetObject("garethmod_lemming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lemming_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_lemming_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_leopard {
            get {
                object obj = ResourceManager.GetObject("garethmod_leopard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_leopard_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_leopard_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lion {
            get {
                object obj = ResourceManager.GetObject("garethmod_lion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lion_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_lion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lioncub {
            get {
                object obj = ResourceManager.GetObject("garethmod_lioncub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_lioncub_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_lioncub_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_oxpecker {
            get {
                object obj = ResourceManager.GetObject("garethmod_oxpecker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_oxpecker_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_oxpecker_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_panther {
            get {
                object obj = ResourceManager.GetObject("garethmod_panther", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_panther_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_panther_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_panthercub {
            get {
                object obj = ResourceManager.GetObject("garethmod_panthercub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_panthercub_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_panthercub_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_pig {
            get {
                object obj = ResourceManager.GetObject("garethmod_pig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_pig_alt {
            get {
                object obj = ResourceManager.GetObject("garethmod_pig_alt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_pig_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_pig_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_piranha {
            get {
                object obj = ResourceManager.GetObject("garethmod_piranha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_piranha_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_piranha_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_sapling {
            get {
                object obj = ResourceManager.GetObject("garethmod_sapling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_sapling_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_sapling_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_shove {
            get {
                object obj = ResourceManager.GetObject("garethmod_shove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_skinwalker {
            get {
                object obj = ResourceManager.GetObject("garethmod_skinwalker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_skinwalker_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_skinwalker_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_snag {
            get {
                object obj = ResourceManager.GetObject("garethmod_snag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_snag_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_snag_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_standoffish {
            get {
                object obj = ResourceManager.GetObject("garethmod_standoffish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_tasmaniandevil {
            get {
                object obj = ResourceManager.GetObject("garethmod_tasmaniandevil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_tasmaniandevil_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_tasmaniandevil_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_tastymorsel {
            get {
                object obj = ResourceManager.GetObject("garethmod_tastymorsel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_treant {
            get {
                object obj = ResourceManager.GetObject("garethmod_treant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_treant_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_treant_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_woundedanimal {
            get {
                object obj = ResourceManager.GetObject("garethmod_woundedanimal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_woundedanimal_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_woundedanimal_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_younglion {
            get {
                object obj = ResourceManager.GetObject("garethmod_younglion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmod_younglion_emission {
            get {
                object obj = ResourceManager.GetObject("garethmod_younglion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] garethmodwatermark {
            get {
                object obj = ResourceManager.GetObject("garethmodwatermark", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
